### ISSUE TITLE
Opentok initialization crash on iOS 15

### ISSUE THREAD

**Issue by britolucaspatrick** [opentok/opentok-ios-sdk-samples-swift#171] opened 2022-01-12 12:20 UTC
![image](https://user-images.githubusercontent.com/35351864/149139178-77da9e6d-23bc-4d1d-8cf0-346781606d78.png)

i am teladoc developer, and this is my error

**Comment by v-kpheng** [comment] 2022-11-02 22:31
Hi, @britolucaspatrick.  Thanks for letting us know about this issue.  That said, some key details, like steps to reproduce are missing, which may make root cause difficult.

I'm going to close this issue.  If this is still reproducible using the latest version of the SDK, can you please refile and answer the questions in the bug report template?  Thanks!

**Closed by v-kpheng** 2022-11-02 22:31 UTC
