### ISSUE TITLE
Urgently ,, i need to know how to switch between built-in mic and speaker during session ,  i try ios documentation still not working , another point i need to know how to mute/unmute voice during session , i had tried the documentation code till now not working???

### ISSUE THREAD

**Issue by Kareem1991** [opentok/opentok-ios-sdk-samples-swift#65] opened 2018-05-01 22:42 UTC

**Comment by Lucashuang0802** [comment] 2018-05-02 17:24
@Kareem1991, we believe that you will have to tear down one publisher if you need to switch to another audio driver. As for mute/unmute of a publisher, you can check out this: https://tokbox.com/developer/sdks/ios/reference/Classes/OTPublisherKit.html#//api/name/publishAudio. For a subscriber, it's in here: https://tokbox.com/developer/sdks/ios/reference/Classes/OTSubscriberKit.html#//api/name/subscribeToAudio

**Comment by muhammadatallah** [comment] 2018-05-02 19:26
@Kareem1991

**Comment by Kareem1991** [comment] 2018-05-02 19:53
@Lucashuang0802 

 first we have already paid for tookbox sdk , i am using ios "SWIFT LANG" and we need support because we have that critical issue in production app in Appstore , we need  to solve together that issue ASAP

 i had already try this  , the voice is not muted  and i will share with you my code

 i try this function and it is not working  : 
===============
func Mute()
{
if IsMuted == true {

                   self.subscriber?.subscribeToAudio = false
                   self.publisher?.publishAudio = false
} else {
                self.subscriber?.subscribeToAudio = false
                   self.publisher?.publishAudio = false }
}
    }

================
i try this function also  and it's not working
================
func Mute()
{
if IsMuted == true {

                   self.publisher?.publishAudio = false
} else {
                self.subscriber?.subscribeToAudio = false
                  }
}
    }



==========================================================================
i  tried this function also as documentation and it 's not working : 
@IBAction func muteMicAction(_ sender: AnyObject) {
        publisher.publishAudio = !publisher.publishAudio
        
        let buttonImage: UIImage  = {
            if !publisher.publishAudio {
                return #imageLiteral(resourceName: "mic_muted-24")
            } else {
                return #imageLiteral(resourceName: "mic-24")
            }
        }()
        
        muteMicButton.setImage(buttonImage, for: .normal)
    }
========================================================
i tried aslo to stop audio track from publisher settings every time i hit the mute button but still the PROBLEM exist and the audio session wasnot muted

SECOND POINT  : 

HOW TO SWITCH BETWEEN BETWEEN SPEAKER & BUILT IN MIC DURING AUDIO SESSION ???

THANKS ,

**Comment by muhammadatallah** [comment] 2018-05-02 20:16
@Lucashuang0802  we need your help please

**Comment by Kareem1991** [comment] 2018-05-02 21:05
@Lucashuang0802 
 i fill out this form before and they directed me to  a link of tokbox documentation .

**Comment by Kareem1991** [comment] 2018-05-06 18:29
@robjperez  Hey!! , the mute problem was solved , 
Second point is not solved yet , i will describe you the issue , in the tokbox when you make audio or video call , by default when publisher talk to subscriber the voice came from speaker and built-in mic
My issue that i had a speaker btn in App UI and i need in the beginning of the call the voice came from mic and when i hit the speaker btn the voice came from speaker and so on ,,,

**Comment by robjperez** [comment] 2018-05-07 08:37
Hi,

Our default implementation does not offer a way to switch between the speaker and the handset speaker (I think when you say `mic` you refer to the handset speaker because the mic cannot reproduce any sound).

If you want to implement that feature, you need to implement your own version of the audio device. I suggest you to take a look to our sample: https://github.com/opentok/opentok-ios-sdk-samples-swift/tree/master/Custom-Audio-Driver
and to our documentation about audio devices: https://tokbox.com/developer/tutorials/ios/custom-audio-driver/

I'm going to close this issue since there isn't a problem with the samples.

**Closed by robjperez** 2018-05-07 08:37 UTC

**Comment by Kareem1991** [comment] 2018-05-07 14:37
Please, first i'm a client not a user and i paid for tokbox so i need support please , listen to me carefully you don't understand me till now and i try to be more clear with you to understand the issue , listen to me : when the session begin and the publisher and subscriber connected  the voice or the audio by default came from speaker and headset to gether , i had asked that i how to make voice came from one port as i need voice came from headset only not both headset and speaker , that is the problem with the sdk and i told you in github that iam using swift not obj c  please listen to me carefully i had a problem and i need to solve the issue ,, and it is not a professional way to close my ticket without being solved , waiting for your response
Thanks
________________________________

**Comment by Kareem1991** [comment] 2018-05-07 17:09
Hi ,
https://tokbox.com/developer/tutorials/ios/swift/basic-video-chat/

If you try this tutorial the voice will came from speaker and headset in both cases audio only and video only the sound came from speaker and headset , go a head with that tutorial and you will see the issue

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Kareem1991** [comment] 2018-05-07 17:14
Hi , i use that tutorial
https://tokbox.com/developer/tutorials/ios/swift/basic-video-chat/
If you test this tutorial you will find the sound came from speaker and headset to gether , in case audio only or video only , you can test it and you will understand the issue ..... and if you have any support sample project in swift that issue is not appeared in , as when i make a call the sound came from headset only you can share please ,
Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by enasaz9** [comment] 2021-09-29 11:25
hello @Kareem1991, I am having the same problem.
Were you able to fix it?
