### ISSUE TITLE
Warning: -[AVCaptureSession startRunning] should be called from background thread

### ISSUE THREAD

**Issue by ClaireRimel** [opentok/opentok-ios-sdk-samples-swift#182] opened 2022-10-27 14:55 UTC
Xcode `14.0`
OpenTok via CocoaPods,  pod version `2.23.1`

I implemented the publisher as showed on the Basic-Video-Chat project but on the instantiation of the Publisher, It's appears a warning `-[AVCaptureSession startRunning] should be called from background thread. Calling it on the main thread can lead to UI unresponsiveness.`

I have tried to set it on background thread, but it doesn't work, because it needs to be set on main thread.  

How this warning can be fixed?

![Screenshot 2022-10-27 at 16 41 45](https://user-images.githubusercontent.com/43319552/198326710-3a65e22a-9559-4088-806c-e8d699292aa0.png)

**Comment by knightcode** [comment] 2022-10-28 20:50
Also having this issue. Calling the constructor in a background thread also complains because the View's initWithFrame: needs to be called on the main thread. So damned either way.

**Comment by v-kpheng** [comment] 2022-11-02 21:47
@ClaireRimel, thanks for letting us know about this issue.  This was fixed in 2.24.0, which was released recently.  See release notes here: https://tokbox.com/developer/sdks/ios/release-notes.html.

<img width="957" alt="image" src="https://user-images.githubusercontent.com/49660118/199608532-abaa6512-8bf2-42bd-9d76-5c422cf4acaf.png">

Since this was fixed, I'm going to close this issue.  If you're still able to reproduce, please let us know.  Thanks!

**Closed by v-kpheng** 2022-11-02 21:47 UTC

**Comment by ClaireRimel** [comment] 2022-11-03 16:51
Thank you @v-kpheng for your answer.

With this 2.4.0 version I observe a latency of 10sec between the call of doPublish() and the call of session.publish(publisher, error: &error) which make the view freezing during the 10sec.
![2 4 0Version](https://user-images.githubusercontent.com/43319552/199782469-fedf843f-9091-40de-8b2a-81fd3319d490.png)


On 2.3.1 version this latency was around 1-2 seconds 
![2 23 1Version](https://user-images.githubusercontent.com/43319552/199782503-7385ee31-0c40-49c1-b399-3fbfe882d19c.png)


Here the Sample of my code 
![code_sample](https://user-images.githubusercontent.com/43319552/199783817-574e3d86-bc9e-43e2-a7d2-7b6593c64df6.png)

How is it possible to reduce this latency?

**Comment by v-kpheng** [comment] 2022-11-09 22:17
> Thank you @v-kpheng for your answer.
> 
> With this 2.4.0 version I observe a latency of 10sec between the call of doPublish() and the call of session.publish(publisher, error: &error) which make the view freezing during the 10sec. ![2 4 0Version](https://user-images.githubusercontent.com/43319552/199782469-fedf843f-9091-40de-8b2a-81fd3319d490.png)
> 
> On 2.3.1 version this latency was around 1-2 seconds ![2 23 1Version](https://user-images.githubusercontent.com/43319552/199782503-7385ee31-0c40-49c1-b399-3fbfe882d19c.png)
> 
> Here the Sample of my code ![code_sample](https://user-images.githubusercontent.com/43319552/199783817-574e3d86-bc9e-43e2-a7d2-7b6593c64df6.png)
> 
> How is it possible to reduce this latency?

@ClaireRimel, can you please file another issue?  Reason being, it seems unrelated to the issue we just closed.  Thanks!
